CREATE TABLE filsafat (
  biblio_id INT NOT NULL,
  gmd_id INT DEFAULT NULL,
  title TEXT NOT NULL,
  sor VARCHAR(200) DEFAULT NULL,
  edition VARCHAR(50) DEFAULT NULL,
  isbn_issn VARCHAR(20) DEFAULT NULL,
  publisher_id INT DEFAULT NULL,
  publish_year VARCHAR(20) DEFAULT NULL,
  collation VARCHAR(50) DEFAULT NULL,
  series_title VARCHAR(200) DEFAULT NULL,
  call_number VARCHAR(50) DEFAULT NULL,
  language_id CHAR(5) DEFAULT 'en',
  source VARCHAR(3) DEFAULT NULL,
  publish_place_id INT DEFAULT NULL,
  classification VARCHAR(40) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  image VARCHAR(100) DEFAULT NULL,
  file_att VARCHAR(255) DEFAULT NULL,
  opac_hide SMALLINT DEFAULT 0,
  promoted SMALLINT DEFAULT 0,
  labels TEXT DEFAULT NULL,
  frequency_id INT NOT NULL DEFAULT 0,
  spec_detail_info TEXT DEFAULT NULL,
  content_type_id INT DEFAULT NULL,
  media_type_id INT DEFAULT NULL,
  carrier_type_id INT DEFAULT NULL,
  input_date TIMESTAMP DEFAULT NULL,
  last_update TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (biblio_id)
);
